ALTER TABLE properties 
ADD COLUMN IF NOT EXISTS description_audio_url TEXT,
ADD COLUMN IF NOT EXISTS video_script TEXT,
ADD COLUMN IF NOT EXISTS background_music_url TEXT,
ADD COLUMN IF NOT EXISTS video_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS audio_enabled BOOLEAN DEFAULT TRUE;
