
import { ProfileData } from "./types";

// Mock database with potential roommates
export const potentialRoommates: ProfileData[] = [
  {
    name: "Alex",
    age: "28",
    gender: "male",
    occupation: "Software Engineer",
    movingDate: "2023-09-01",
    budget: [800, 1200],
    location: "Downtown",
    cleanliness: 80,
    pets: false,
    smoking: false,
    drinking: "sometimes",
    guests: "rarely",
    sleepSchedule: "normal",
    workSchedule: "9AM-5PM",
    interests: ["Fitness", "Tech", "Gaming", "Cooking"],
    traits: ["Clean", "Responsible", "Quiet", "Organized", "Reliable"],
    preferredLiving: "findRoommate"
  },
  {
    name: "Jamie",
    age: "25",
    gender: "non-binary",
    occupation: "Graduate Student",
    movingDate: "2023-09-15",
    budget: [750, 1100],
    location: "University District",
    cleanliness: 60,
    pets: true,
    smoking: false,
    drinking: "sometimes",
    guests: "sometimes",
    sleepSchedule: "night",
    workSchedule: "Flexible",
    interests: ["Reading", "Movies", "Pets", "Music"],
    traits: ["Adaptable", "Sociable", "Friendly", "Easygoing", "Considerate"],
    preferredLiving: "findRoommate"
  },
  {
    name: "Taylor",
    age: "31",
    gender: "female",
    occupation: "Marketing Manager",
    movingDate: "2023-08-20",
    budget: [900, 1500],
    location: "Ballard",
    cleanliness: 90,
    pets: false,
    smoking: false,
    drinking: "rarely",
    guests: "sometimes",
    sleepSchedule: "early",
    workSchedule: "8AM-4PM",
    interests: ["Fitness", "Travel", "Cooking", "Outdoors"],
    traits: ["Clean", "Organized", "Punctual", "Responsible", "Communicative"],
    preferredLiving: "shareProperty",
    propertyDetails: {
      propertyType: "apartment",
      bedrooms: 2,
      bathrooms: 1,
      address: "123 Main St, Ballard"
    }
  },
  {
    name: "Jordan",
    age: "26",
    gender: "male",
    occupation: "Graphic Designer",
    movingDate: "2023-10-01",
    budget: [700, 1100],
    location: "Capitol Hill",
    cleanliness: 50,
    pets: true,
    smoking: true,
    drinking: "often",
    guests: "often",
    sleepSchedule: "night",
    workSchedule: "10AM-6PM",
    interests: ["Art", "Music", "Gaming", "Photography"],
    traits: ["Creative", "Sociable", "Easygoing", "Adaptable", "Friendly"],
    preferredLiving: "findRoommate"
  },
  {
    name: "Morgan",
    age: "29",
    gender: "female",
    occupation: "Nurse",
    movingDate: "2023-09-10",
    budget: [850, 1300],
    location: "Queen Anne",
    cleanliness: 85,
    pets: false,
    smoking: false,
    drinking: "rarely",
    guests: "rarely",
    sleepSchedule: "variable",
    workSchedule: "Night Shift 11PM-7AM",
    interests: ["Fitness", "Reading", "Cooking", "Travel"],
    traits: ["Clean", "Quiet", "Respectful", "Reliable", "Considerate"],
    preferredLiving: "shareProperty",
    propertyDetails: {
      propertyType: "house",
      bedrooms: 3,
      bathrooms: 2,
      address: "456 Oak St, Queen Anne"
    }
  },
  {
    name: "Casey",
    age: "32",
    gender: "non-binary",
    occupation: "Teacher",
    movingDate: "2023-08-15",
    budget: [800, 1100],
    location: "Fremont",
    cleanliness: 70,
    pets: true,
    smoking: false,
    drinking: "sometimes",
    guests: "sometimes",
    sleepSchedule: "early",
    workSchedule: "7AM-3PM",
    interests: ["Reading", "Sports", "Cooking", "Movies"],
    traits: ["Patient", "Communicative", "Friendly", "Organized", "Reliable"],
    preferredLiving: "findRoommate"
  },
];
