-- Insert comprehensive mock roommate data for testing the matching algorithm
-- These profiles cover diverse backgrounds, preferences, and importance levels

INSERT INTO public.roommate (
  user_id, full_name, age, gender, email, phone_number, linkedin_profile,
  nationality, language, ethnicity, religion, occupation,
  preferred_location, budget_range, move_in_date_start, move_in_date_end,
  housing_type, living_space, smoking, lives_with_smokers, has_pets, pet_type,
  work_location, work_schedule, hobbies, diet, diet_other,
  pet_preference, roommate_gender_preference, roommate_lifestyle_preference, important_roommate_traits,
  age_range_preference, gender_preference, nationality_preference, nationality_custom,
  language_preference, language_specific, dietary_preferences, dietary_other,
  occupation_preference, occupation_specific, work_schedule_preference,
  ethnicity_preference, ethnicity_other, religion_preference, religion_other,
  pet_preference_enum, pet_specification, smoking_preference, roommate_hobbies, rent_option,
  age_range_preference_importance, gender_preference_importance, nationality_preference_importance,
  language_preference_importance, dietary_preferences_importance, occupation_preference_importance,
  work_schedule_preference_importance, ethnicity_preference_importance, religion_preference_importance,
  pet_preference_importance, smoking_preference_importance
) VALUES 

-- User 1: Sarah Chen - Young Tech Professional
(
  '11111111-1111-1111-1111-111111111111',
  'Sarah Chen',
  25,
  'Female',
  'sarah.chen@example.com',
  '+1-555-0101',
  'https://linkedin.com/in/sarah-chen',
  'Chinese',
  'Mandarin',
  'Asian',
  'Buddhist',
  'Software Engineer',
  ARRAY['Downtown', 'Tech District', 'University Area'],
  ARRAY[1200, 1800],
  '2024-03-01',
  '2024-04-15',
  'apartment',
  'privateRoom',
  false,
  false,
  false,
  null,
  'hybrid',
  'dayShift',
  ARRAY['coding', 'yoga', 'cooking', 'reading'],
  'vegetarian',
  null,
  'No pets',
  'Female',
  'Clean and professional',
  ARRAY['clean', 'quiet', 'professional', 'tech-savvy'],
  ARRAY[22, 30],
  ARRAY['Female', 'Non-binary'],
  'custom',
  'Chinese, Korean, Japanese',
  'specific',
  'Mandarin, English',
  'vegetarian',
  null,
  true,
  'Software Engineer, Data Scientist, UX Designer',
  'dayShift',
  'same',
  null,
  'noPreference',
  null,
  'noPets',
  null,
  'noSmoking',
  ARRAY['yoga', 'cooking', 'tech meetups'],
  'findTogether',
  'important',
  'must',
  'important',
  'important',
  'must',
  'important',
  'important',
  'notImportant',
  'notImportant',
  'must',
  'must'
),

-- User 2: Marcus Johnson - Creative Professional
(
  '22222222-2222-2222-2222-222222222222',
  'Marcus Johnson',
  28,
  'Male',
  'marcus.johnson@example.com',
  '+1-555-0102',
  'https://linkedin.com/in/marcus-johnson',
  'American',
  'English',
  'African American',
  'Christian',
  'Graphic Designer',
  ARRAY['Creative Hub', 'Arts District', 'Downtown'],
  ARRAY[1000, 1500],
  '2024-02-15',
  '2024-03-30',
  'house',
  'privateRoom',
  false,
  false,
  true,
  'Cat',
  'remote',
  'afternoonShift',
  ARRAY['photography', 'music', 'art galleries', 'basketball'],
  'noPreference',
  null,
  'Cat ok',
  'Any',
  'Creative and social',
  ARRAY['creative', 'social', 'artistic', 'relaxed'],
  ARRAY[25, 35],
  ARRAY['Male', 'Female'],
  'noPreference',
  null,
  'noPreference',
  null,
  'noPreference',
  null,
  false,
  null,
  'noPreference',
  'noPreference',
  null,
  'noPreference',
  null,
  'catOk',
  'No aggressive dogs',
  'noSmoking',
  ARRAY['music', 'art', 'photography'],
  'joinExisting',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'notImportant',
  'important',
  'important'
),

-- User 3: Priya Patel - Medical Student
(
  '33333333-3333-3333-3333-333333333333',
  'Priya Patel',
  23,
  'Female',
  'priya.patel@example.com',
  '+1-555-0103',
  'https://linkedin.com/in/priya-patel',
  'Indian',
  'Hindi',
  'South Asian',
  'Hindu',
  'Medical Student',
  ARRAY['University Area', 'Medical District', 'Suburbs'],
  ARRAY[800, 1200],
  '2024-01-15',
  '2024-02-28',
  'apartment',
  'privateRoom',
  false,
  false,
  false,
  null,
  'office',
  'overnightShift',
  ARRAY['studying', 'meditation', 'bollywood dancing', 'volunteering'],
  'vegetarian',
  null,
  'No pets',
  'Female',
  'Studious and respectful',
  ARRAY['studious', 'quiet', 'respectful', 'health-conscious'],
  ARRAY[20, 28],
  ARRAY['Female'],
  'sameCountry',
  null,
  'sameLanguage',
  null,
  'vegetarian',
  null,
  true,
  'Medical Student, Nurse, Healthcare Professional',
  'opposite',
  'same',
  null,
  'same',
  null,
  'noPets',
  null,
  'noSmoking',
  ARRAY['studying', 'meditation', 'cultural activities'],
  'findTogether',
  'important',
  'must',
  'must',
  'must',
  'must',
  'important',
  'important',
  'must',
  'must',
  'must',
  'must'
),

-- User 4: Alex Rodriguez - Finance Professional
(
  '44444444-4444-4444-4444-444444444444',
  'Alex Rodriguez',
  30,
  'Male',
  'alex.rodriguez@example.com',
  '+1-555-0104',
  'https://linkedin.com/in/alex-rodriguez',
  'Mexican',
  'Spanish',
  'Hispanic',
  'Catholic',
  'Financial Analyst',
  ARRAY['Financial District', 'Downtown', 'Uptown'],
  ARRAY[1500, 2200],
  '2024-03-15',
  '2024-05-01',
  'apartment',
  'privateRoom',
  false,
  true,
  false,
  null,
  'office',
  'dayShift',
  ARRAY['soccer', 'cooking', 'traveling', 'salsa dancing'],
  'halal',
  null,
  'No pets',
  'Male',
  'Professional and social',
  ARRAY['professional', 'social', 'organized', 'multicultural'],
  ARRAY[26, 35],
  ARRAY['Male', 'Female'],
  'custom',
  'Mexican, Latin American, Spanish',
  'specific',
  'Spanish, English',
  'halal',
  null,
  true,
  'Financial Analyst, Investment Banker, Accountant',
  'dayShift',
  'same',
  null,
  'same',
  null,
  'noPets',
  null,
  'socialOk',
  ARRAY['soccer', 'cooking', 'dancing'],
  'findTogether',
  'important',
  'important',
  'important',
  'important',
  'must',
  'important',
  'important',
  'important',
  'important',
  'must',
  'notImportant'
),

-- User 5: Emma Thompson - Graduate Student
(
  '55555555-5555-5555-5555-555555555555',
  'Emma Thompson',
  26,
  'Female',
  'emma.thompson@example.com',
  '+1-555-0105',
  'https://linkedin.com/in/emma-thompson',
  'British',
  'English',
  'Caucasian',
  'Agnostic',
  'PhD Student',
  ARRAY['University Area', 'Library District', 'Quiet Suburbs'],
  ARRAY[700, 1100],
  '2024-02-01',
  '2024-03-15',
  'house',
  'sharedRoom',
  false,
  false,
  true,
  'Small dog',
  'hybrid',
  'afternoonShift',
  ARRAY['research', 'hiking', 'book clubs', 'podcasts'],
  'noPreference',
  null,
  'Small pets ok',
  'Female',
  'Academic and thoughtful',
  ARRAY['academic', 'thoughtful', 'environmentally conscious', 'quiet'],
  ARRAY[23, 32],
  ARRAY['Female', 'Non-binary'],
  'noPreference',
  null,
  'noPreference',
  null,
  'noPreference',
  null,
  true,
  'PhD Student, Researcher, Professor, Librarian',
  'afternoonShift',
  'noPreference',
  null,
  'noPreference',
  null,
  'smallPetsOk',
  'No large dogs or exotic pets',
  'noSmoking',
  ARRAY['reading', 'hiking', 'environmental activism'],
  'findTogether',
  'important',
  'important',
  'notImportant',
  'notImportant',
  'notImportant',
  'important',
  'important',
  'notImportant',
  'notImportant',
  'important',
  'must'
),

-- User 6: David Kim - Chef
(
  '66666666-6666-6666-6666-666666666666',
  'David Kim',
  29,
  'Male',
  'david.kim@example.com',
  '+1-555-0106',
  'https://linkedin.com/in/david-kim',
  'Korean',
  'Korean',
  'Asian',
  'Christian',
  'Chef',
  ARRAY['Restaurant District', 'Koreatown', 'Downtown'],
  ARRAY[1100, 1600],
  '2024-03-01',
  '2024-04-30',
  'apartment',
  'privateRoom',
  false,
  false,
  false,
  null,
  'office',
  'overnightShift',
  ARRAY['cooking', 'food photography', 'wine tasting', 'martial arts'],
  'kosher',
  null,
  'No pets',
  'Any',
  'Culinary enthusiast',
  ARRAY['culinary', 'creative', 'night owl', 'cultural'],
  ARRAY[25, 35],
  ARRAY['Male', 'Female'],
  'sameCountry',
  null,
  'sameLanguage',
  null,
  'kosher',
  null,
  true,
  'Chef, Cook, Food Critic, Restaurant Manager',
  'overnightShift',
  'same',
  null,
  'same',
  null,
  'noPets',
  null,
  'noSmoking',
  ARRAY['cooking', 'food culture', 'martial arts'],
  'joinExisting',
  'important',
  'notImportant',
  'important',
  'important',
  'must',
  'important',
  'must',
  'important',
  'important',
  'must',
  'must'
),

-- User 7: Jessica Williams - Nurse
(
  '77777777-7777-7777-7777-777777777777',
  'Jessica Williams',
  27,
  'Female',
  'jessica.williams@example.com',
  '+1-555-0107',
  'https://linkedin.com/in/jessica-williams',
  'American',
  'English',
  'Mixed Race',
  'Christian',
  'Nurse',
  ARRAY['Medical District', 'Hospital Area', 'Suburbs'],
  ARRAY[900, 1400],
  '2024-02-15',
  '2024-04-01',
  'apartment',
  'privateRoom',
  false,
  false,
  true,
  'Two cats',
  'office',
  'overnightShift',
  ARRAY['fitness', 'cat care', 'volunteering', 'board games'],
  'noPreference',
  null,
  'Cat lover',
  'Female',
  'Caring and reliable',
  ARRAY['caring', 'reliable', 'health-conscious', 'animal lover'],
  ARRAY[24, 32],
  ARRAY['Female'],
  'noPreference',
  null,
  'noPreference',
  null,
  'noPreference',
  null,
  true,
  'Nurse, Doctor, Medical Assistant, Healthcare Worker',
  'overnightShift',
  'noPreference',
  null,
  'noPreference',
  null,
  'catOk',
  'Must love cats',
  'noSmoking',
  ARRAY['fitness', 'animal care', 'healthcare advocacy'],
  'findTogether',
  'important',
  'must',
  'notImportant',
  'notImportant',
  'notImportant',
  'important',
  'must',
  'notImportant',
  'notImportant',
  'must',
  'must'
),

-- User 8: Ahmed Hassan - Computer Science Student
(
  '88888888-8888-8888-8888-888888888888',
  'Ahmed Hassan',
  22,
  'Male',
  'ahmed.hassan@example.com',
  '+1-555-0108',
  'https://linkedin.com/in/ahmed-hassan',
  'Egyptian',
  'Arabic',
  'Middle Eastern',
  'Muslim',
  'Computer Science Student',
  ARRAY['University Area', 'Tech District', 'International Student Housing'],
  ARRAY[600, 1000],
  '2024-01-20',
  '2024-03-01',
  'apartment',
  'sharedRoom',
  false,
  false,
  false,
  null,
  'hybrid',
  'dayShift',
  ARRAY['programming', 'gaming', 'soccer', 'chess'],
  'halal',
  null,
  'No pets',
  'Male',
  'Studious and respectful',
  ARRAY['studious', 'respectful', 'international', 'tech-oriented'],
  ARRAY[20, 26],
  ARRAY['Male'],
  'custom',
  'Middle Eastern, North African, Muslim',
  'specific',
  'Arabic, English',
  'halal',
  null,
  true,
  'Computer Science Student, Software Engineer, IT Professional',
  'dayShift',
  'same',
  null,
  'same',
  null,
  'noPets',
  null,
  'noSmoking',
  ARRAY['programming', 'gaming', 'soccer'],
  'findTogether',
  'important',
  'must',
  'must',
  'must',
  'must',
  'important',
  'important',
  'must',
  'must',
  'must',
  'must'
),

-- User 9: Lisa Chang - Marketing Manager
(
  '99999999-9999-9999-9999-999999999999',
  'Lisa Chang',
  31,
  'Female',
  'lisa.chang@example.com',
  '+1-555-0109',
  'https://linkedin.com/in/lisa-chang',
  'Taiwanese',
  'Mandarin',
  'Asian',
  'Buddhist',
  'Marketing Manager',
  ARRAY['Business District', 'Downtown', 'Modern Apartments'],
  ARRAY[1600, 2400],
  '2024-04-01',
  '2024-06-01',
  'apartment',
  'privateRoom',
  false,
  false,
  true,
  'Small dog',
  'hybrid',
  'dayShift',
  ARRAY['yoga', 'wine tasting', 'networking', 'travel'],
  'vegetarian',
  null,
  'Small pets ok',
  'Female',
  'Professional and social',
  ARRAY['professional', 'social', 'organized', 'wellness-focused'],
  ARRAY[28, 38],
  ARRAY['Female'],
  'custom',
  'Taiwanese, Chinese, Asian',
  'specific',
  'Mandarin, English',
  'vegetarian',
  null,
  true,
  'Marketing Manager, Business Development, Sales Manager',
  'dayShift',
  'same',
  null,
  'noPreference',
  null,
  'smallPetsOk',
  'Small, well-behaved pets only',
  'noSmoking',
  ARRAY['yoga', 'networking', 'wellness activities'],
  'findTogether',
  'important',
  'must',
  'important',
  'important',
  'must',
  'important',
  'important',
  'important',
  'notImportant',
  'important',
  'must'
),

-- User 10: James O'Connor - Graduate Student
(
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'James O''Connor',
  24,
  'Male',
  'james.oconnor@example.com',
  '+1-555-0110',
  'https://linkedin.com/in/james-oconnor',
  'Irish',
  'English',
  'Caucasian',
  'Catholic',
  'MBA Student',
  ARRAY['University Area', 'Business District', 'Graduate Housing'],
  ARRAY[1000, 1500],
  '2024-02-20',
  '2024-04-15',
  'house',
  'privateRoom',
  false,
  true,
  false,
  null,
  'hybrid',
  'dayShift',
  ARRAY['rugby', 'business networking', 'pub trivia', 'hiking'],
  'noPreference',
  null,
  'No pets',
  'Male',
  'Ambitious and social',
  ARRAY['ambitious', 'social', 'athletic', 'business-minded'],
  ARRAY[22, 30],
  ARRAY['Male', 'Female'],
  'custom',
  'Irish, European, Western',
  'noPreference',
  null,
  'noPreference',
  null,
  true,
  'MBA Student, Business Analyst, Consultant, Manager',
  'dayShift',
  'same',
  null,
  'same',
  null,
  'noPets',
  null,
  'socialOk',
  ARRAY['rugby', 'business networking', 'outdoor activities'],
  'findTogether',
  'important',
  'important',
  'important',
  'notImportant',
  'notImportant',
  'important',
  'important',
  'important',
  'important',
  'must',
  'notImportant'
);

-- Verify the data was inserted correctly
SELECT 
  full_name, 
  nationality, 
  language, 
  occupation, 
  ARRAY_LENGTH(preferred_location, 1) as location_count,
  budget_range,
  dietary_preferences,
  occupation_preference_importance
FROM public.roommate 
ORDER BY full_name; 