-- Insert mock data into roommate table
INSERT INTO public.roommate (user_id, full_name, email, age, gender, phone_number, preferred_location, budget_range, move_in_date, housing_type, living_space, has_pets, smoking, lives_with_smokers, diet, work_location, work_schedule, pet_preference, roommate_gender_preference, roommate_lifestyle_preference, hobbies, important_roommate_traits, linkedin_profile, created_at, updated_at) VALUES
('11111111-1111-1111-1111-111111111111', 'Mock Alex Johnson', 'mock.alex.johnson@example.com', 25, 'Male', '+1234567890', 'Downtown', '$1200-$1800', '2024-02-01', 'Apartment', 'Shared', false, false, false, 'Omnivore', 'Tech District', '9AM-5PM', 'No pets', 'Any', 'Clean and quiet', ARRAY['coding', 'gaming', 'hiking'], ARRAY['organized', 'quiet', 'friendly'], 'https://linkedin.com/in/mock-alex-johnson', now(), now()),
('22222222-2222-2222-2222-222222222222', 'Mock Sarah Chen', 'mock.sarah.chen@example.com', 28, 'Female', '+1234567891', 'Midtown', '$1000-$1600', '2024-03-15', 'Apartment', 'Shared', true, false, false, 'Vegetarian', 'Business District', '8AM-4PM', 'Cat friendly', 'Female preferred', 'Active lifestyle', ARRAY['yoga', 'reading', 'cooking'], ARRAY['clean', 'respectful', 'active'], 'https://linkedin.com/in/mock-sarah-chen', now(), now()),
('33333333-3333-3333-3333-333333333333', 'Mock Mike Rodriguez', 'mock.mike.rodriguez@example.com', 30, 'Male', '+1234567892', 'Arts District', '$800-$1400', '2024-04-01', 'Loft', 'Private room', false, false, true, 'Omnivore', 'Creative Hub', '10AM-6PM', 'No pets', 'Any', 'Creative and social', ARRAY['art', 'photography', 'music'], ARRAY['creative', 'social', 'easygoing'], 'https://linkedin.com/in/mock-mike-rodriguez', now(), now()),
('44444444-4444-4444-4444-444444444444', 'Mock Emily Davis', 'mock.emily.davis@example.com', 26, 'Female', '+1234567893', 'Medical District', '$900-$1300', '2024-05-01', 'Apartment', 'Shared', true, false, false, 'Pescatarian', 'Hospital Area', 'Rotating shifts', 'Dog friendly', 'Female preferred', 'Quiet and clean', ARRAY['fitness', 'cooking', 'volunteering'], ARRAY['responsible', 'clean', 'caring'], 'https://linkedin.com/in/mock-emily-davis', now(), now()),
('55555555-5555-5555-5555-555555555555', 'Mock Ryan Wilson', 'mock.ryan.wilson@example.com', 29, 'Male', '+1234567894', 'Financial District', '$1500-$2200', '2024-06-01', 'High-rise', 'Private room', false, false, false, 'Omnivore', 'Wall Street', '7AM-3PM', 'No pets', 'Male preferred', 'Professional and quiet', ARRAY['finance', 'running', 'reading'], ARRAY['professional', 'organized', 'ambitious'], 'https://linkedin.com/in/mock-ryan-wilson', now(), now()),
('66666666-6666-6666-6666-666666666666', 'Mock Jessica Liu', 'mock.jessica.liu@example.com', 24, 'Female', '+1234567895', 'University Area', '$600-$1000', '2024-07-01', 'Shared house', 'Shared', false, false, false, 'Vegan', 'Campus', 'Flexible', 'Any pets', 'Any', 'Studious and friendly', ARRAY['studying', 'language learning', 'travel'], ARRAY['studious', 'international', 'friendly'], 'https://linkedin.com/in/mock-jessica-liu', now(), now()),
('77777777-7777-7777-7777-777777777777', 'Mock Carlos Martinez', 'mock.carlos.martinez@example.com', 32, 'Male', '+1234567896', 'Restaurant District', '$1000-$1500', '2024-08-01', 'Apartment', 'Private room', false, false, false, 'Omnivore', 'Various locations', 'Evening shifts', 'No pets', 'Any', 'Food lover and social', ARRAY['cooking', 'food tasting', 'socializing'], ARRAY['culinary', 'social', 'night owl'], 'https://linkedin.com/in/mock-carlos-martinez', now(), now()),
('88888888-8888-8888-8888-888888888888', 'Mock Amanda Thompson', 'mock.amanda.thompson@example.com', 27, 'Female', '+1234567897', 'Suburban', '$700-$1100', '2024-09-01', 'Townhouse', 'Shared', true, false, false, 'Vegetarian', 'School District', '7AM-3PM', 'Cat friendly', 'Female preferred', 'Family-oriented', ARRAY['teaching', 'gardening', 'crafts'], ARRAY['nurturing', 'organized', 'patient'], 'https://linkedin.com/in/mock-amanda-thompson', now(), now()),
('99999999-9999-9999-9999-999999999999', 'Mock Kevin Park', 'mock.kevin.park@example.com', 31, 'Male', '+1234567898', 'Tech Hub', '$1300-$1900', '2024-10-01', 'Modern apartment', 'Private room', false, false, false, 'Omnivore', 'Tech Campus', '9AM-5PM', 'No pets', 'Any', 'Tech-savvy and analytical', ARRAY['data analysis', 'machine learning', 'gaming'], ARRAY['analytical', 'tech-savvy', 'quiet'], 'https://linkedin.com/in/mock-kevin-park', now(), now()),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Mock Sophia Williams', 'mock.sophia.williams@example.com', 23, 'Female', '+1234567899', 'Trendy District', '$800-$1200', '2024-11-01', 'Loft', 'Shared', true, false, false, 'Flexitarian', 'Digital Hub', 'Flexible hours', 'Small pets ok', 'Any', 'Creative and outgoing', ARRAY['social media', 'photography', 'events'], ARRAY['creative', 'outgoing', 'trendy'], 'https://linkedin.com/in/mock-sophia-williams', now(), now())
ON CONFLICT (user_id) DO NOTHING;

-- Insert mock data into co_owner table
INSERT INTO public.co_owner (user_id, full_name, email, age, occupation, phone_number, preferred_location, investment_capacity, investment_timeline, property_type, co_ownership_experience, created_at, updated_at) VALUES
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Mock Robert Johnson', 'mock.robert.johnson@example.com', 35, 'Investment Banker', '+1234567800', 'Manhattan', ARRAY[500000, 800000], '6-12 months', 'Luxury Condo', 'Experienced', now(), now()),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 'Mock Linda Chen', 'mock.linda.chen@example.com', 42, 'Real Estate Agent', '+1234567801', 'Brooklyn', ARRAY[300000, 500000], '3-6 months', 'Townhouse', 'Expert', now(), now()),
('dddddddd-dddd-dddd-dddd-dddddddddddd', 'Mock Michael Brown', 'mock.michael.brown@example.com', 38, 'Software Architect', '+1234567802', 'Queens', ARRAY[400000, 600000], '12-18 months', 'Single Family Home', 'Intermediate', now(), now()),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'Mock Patricia Davis', 'mock.patricia.davis@example.com', 45, 'Doctor', '+1234567803', 'Westchester', ARRAY[600000, 900000], '6-12 months', 'Luxury Home', 'Beginner', now(), now()),
('ffffffff-ffff-ffff-ffff-ffffffffffff', 'Mock Christopher Wilson', 'mock.christopher.wilson@example.com', 33, 'Entrepreneur', '+1234567804', 'New Jersey', ARRAY[250000, 400000], '3-6 months', 'Condo', 'Experienced', now(), now()),
('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee', 'Mock Margaret Garcia', 'mock.margaret.garcia@example.com', 40, 'Lawyer', '+1234567805', 'Long Island', ARRAY[450000, 700000], '12-24 months', 'Single Family Home', 'Intermediate', now(), now()),
('bbbbbbbb-cccc-dddd-eeee-ffffffffffff', 'Mock Daniel Rodriguez', 'mock.daniel.rodriguez@example.com', 36, 'Finance Director', '+1234567806', 'Connecticut', ARRAY[350000, 550000], '6-12 months', 'Townhouse', 'Beginner', now(), now()),
('cccccccc-dddd-eeee-ffff-aaaaaaaaaaaa', 'Mock Elizabeth Martinez', 'mock.elizabeth.martinez@example.com', 41, 'Marketing Director', '+1234567807', 'Staten Island', ARRAY[300000, 450000], '3-6 months', 'Condo', 'Experienced', now(), now()),
('dddddddd-eeee-ffff-aaaa-bbbbbbbbbbbb', 'Mock Anthony Taylor', 'mock.anthony.taylor@example.com', 39, 'Consultant', '+1234567808', 'Bronx', ARRAY[200000, 350000], '12-18 months', 'Apartment', 'Intermediate', now(), now()),
('eeeeeeee-ffff-aaaa-bbbb-cccccccccccc', 'Mock Mary Anderson', 'mock.mary.anderson@example.com', 37, 'Executive', '+1234567809', 'Yonkers', ARRAY[400000, 650000], '6-12 months', 'Luxury Condo', 'Beginner', now(), now())
ON CONFLICT (user_id) DO NOTHING;

-- Insert mock data into Both table (note: case-sensitive table name)
INSERT INTO public."Both" (user_id, full_name, email, created_at, updated_at) VALUES
('ffffffff-aaaa-bbbb-cccc-dddddddddddd', 'Mock Jennifer Lopez', 'mock.jennifer.lopez@example.com', now(), now()),
('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeef', 'Mock William Smith', 'mock.william.smith@example.com', now(), now()),
('bbbbbbbb-cccc-dddd-eeee-ffffffffffff', 'Mock Ashley Johnson', 'mock.ashley.johnson@example.com', now(), now()),
('cccccccc-dddd-eeee-ffff-aaaaaaaaaa11', 'Mock Matthew Davis', 'mock.matthew.davis@example.com', now(), now()),
('dddddddd-eeee-ffff-aaaa-bbbbbbbbbb22', 'Mock Nicole Wilson', 'mock.nicole.wilson@example.com', now(), now()),
('eeeeeeee-ffff-aaaa-bbbb-cccccccccc33', 'Mock Joshua Brown', 'mock.joshua.brown@example.com', now(), now()),
('ffffffff-aaaa-bbbb-cccc-dddddddddd44', 'Mock Stephanie Garcia', 'mock.stephanie.garcia@example.com', now(), now()),
('11111111-bbbb-cccc-dddd-eeeeeeeeee55', 'Mock Andrew Miller', 'mock.andrew.miller@example.com', now(), now()),
('22222222-cccc-dddd-eeee-ffffffffff66', 'Mock Michelle Rodriguez', 'mock.michelle.rodriguez@example.com', now(), now()),
('33333333-dddd-eeee-ffff-aaaaaaaaa777', 'Mock Tyler Martinez', 'mock.tyler.martinez@example.com', now(), now())
ON CONFLICT (user_id) DO NOTHING;