
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase-override';

const SUPABASE_URL = "https://yxppcpzqqolvkpzxuqfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cHBjcHpxcW9sdmtwenh1cWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDMzMzksImV4cCI6MjA2NjYxOTMzOX0.Lv4nPWSiqL_cK9trxSjfWWbjrDEPeU501_AW5M-k3dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
